# Project: VirtualGlove
# File: src/powerglove_vision/academy_web.py
# Purpose: Render Glove Academy lessons and personal hand setup.
# Author: Iain Bennett
# Copyright (c) 2026 Iain Bennett
# SPDX-License-Identifier: MIT
# Full history: docs/CHANGELOG.md and Git history.
# Change log:
#   2026-09-06 - Separate maintained web modules without changing rendered pages.

"""Render Glove Academy lessons and personal hand setup."""

from .web_common import _page, VISION_STARTUP_SCRIPT
from .player_web import PLAYER_SELECTOR_CONTENT, PLAYER_SCRIPT
from .tuning_web import TUNE_CONTENT, TUNE_SCRIPT, TUNE_THRESHOLDS

LEARN = _page(
    "Glove Academy",
    """<h1>Glove Academy</h1><p class='lead dashboard-lead'>Practice gesture recognition without a RetroPie connection. Pixel Pal will guide you through 16 fun lessons so your hand can become the controller. Follow the pictures, try each gesture, and watch the lesson respond. Your console controls stay safely paused while you learn.</p>
<div class=learn-grid><div class=learn-camera><img class=camera id=learn-camera data-src=/stream alt='Live camera view for gesture practice'><div class=camera-centre-target id=learn-camera-target hidden aria-hidden=true></div><div class=camera-idle id=learn-startup role=status aria-live=polite></div><div class=practice-badge>● PRACTICE ONLY</div></div>
<section class=card><div id=achievement hidden role=status aria-live=polite style="text-align:center;padding:24px;border:2px solid #36dbe8;border-radius:16px;background:linear-gradient(135deg,#12334b,#261944)"><img class="pixel-pal pal-celebration" src="/help-assets/gestures/v2/pixel-pal-gold-cup.png" alt="Pixel Pal holds a golden award cup" width="180" height="200"><h2>Glove Master!</h2><p>All lessons completed. You're ready to play.</p><button id=restart-training type=button>Start again</button><a class=button href=/dashboard>Go to Dashboard</a></div><div id=lesson-content><div class=lesson-number id=lesson-number>Lesson 1 of 16</div><div class=lesson-title id=lesson-title>Show your hand</div><img id=lesson-image alt="Gesture example" style="display:block;width:100%;height:180px;object-fit:contain;background:#f8f9fc;border-radius:10px"><p class=lesson-cue id=lesson-cue>Hold one hand inside the camera frame with your palm facing the camera.</p>
<details><summary>Live hand measurements</summary><canvas id=hand-detail width=300 height=220 style="width:100%;max-width:300px;background:#090b11" aria-label="Magnified hand landmarks"></canvas><p id=finger-feedback></p><p id=depth-feedback></p></details><div class=lesson-result id=lesson-result>Waiting for your hand…</div><div class=lesson-progress id=lesson-progress></div>
<div class=controls><button id=previous type=button>Previous</button><button id=next type=button>Skip lesson</button><button id=center type=button>Center hand</button></div>
<div class=bits id=practice-actions aria-label="Practice actions"></div><div class=live-readout><div><span class=label>Tracking</span><strong id=tracking>—</strong></div><div><span class=label>Recognized</span><strong id=recognized>None</strong></div><div><span class=label>Confidence</span><strong id=confidence>0%</strong></div></div></div></section></div>""",
    VISION_STARTUP_SCRIPT + r"""const $=id=>document.getElementById(id);
let calibrationPending=false,calibrationSeen=false,calibrationStarted=0,calibrationDoneUntil=0;
function updateCalibration(s){const b=$('center');if(s.calibrating){calibrationSeen=true;calibrationPending=true;if(!calibrationStarted)calibrationStarted=Date.now()}
if(calibrationPending&&calibrationSeen&&s.calibrated&&!s.calibrating){calibrationPending=false;calibrationSeen=false;calibrationStarted=0;calibrationDoneUntil=Date.now()+1800}
if(calibrationPending&&Date.now()-calibrationStarted>20000){calibrationPending=false;calibrationSeen=false;calibrationStarted=0;b.title='Calibration did not finish. Show a relaxed hand and try again.'}
b.disabled=s.vision_state!=='active'||calibrationPending;b.classList.toggle('danger',calibrationPending);b.setAttribute('aria-busy',String(calibrationPending));const text=calibrationPending?'Centering…':Date.now()<calibrationDoneUntil?'Center saved ✓':'Center hand';if(b.textContent!==text)b.textContent=text;}
async function calibrate(){if(calibrationPending)return;calibrationPending=true;calibrationSeen=false;calibrationStarted=Date.now();calibrationDoneUntil=0;updateCalibration({vision_state:'active'});try{const r=await fetch('/calibrate',{method:'POST'});if(!r.ok)throw Error('Calibration request failed');}catch(e){calibrationPending=false;calibrationStarted=0;updateCalibration({vision_state:'active'});$('center').textContent='Retry calibration';$('center').title=e.message}}

const lessons=[
 {title:'Show your hand',image:'show-your-hand.png',cue:'Hold one hand inside the camera frame with your palm facing the camera.',ok:s=>s.detected,result:'Hand found — great!' },
 {title:'Find neutral',image:'find-neutral.png',cue:'Keep your palm centered and relaxed. Your saved center changes only if you select Center hand.',ok:s=>s.detected&&s.calibrated&&!Object.values(s.dpad||{}).some(Boolean),result:'You are in the neutral area.'},
 {title:'Move left',image:'move-left.png',instant:true,cue:'Move your whole hand a short distance left from center.',ok:s=>s.dpad?.left,result:'LEFT recognized.'},
 {title:'Move right',image:'move-right.png',instant:true,cue:'Move your whole hand a short distance right from center.',ok:s=>s.dpad?.right,result:'RIGHT recognized.'},
 {title:'Move up',image:'move-up.png',instant:true,cue:'Raise your whole hand a short distance above center.',ok:s=>s.dpad?.up,result:'UP recognized.'},
 {title:'Move down',image:'move-down.png',instant:true,cue:'Lower your whole hand a short distance below center.',ok:s=>s.dpad?.down,result:'DOWN recognized.'},
 {title:'A — curl your index finger',image:'finger-curl.png',cue:'Keep your palm visible and curl your index finger toward it.',ok:s=>!!s.finger_active?.index&&!s.menu_gesture?.pose,result:'A recognized.'},
 {title:'B — curl your thumb',image:'thumb-curl.png',cue:'Fold your thumb toward your palm while keeping your other fingers relaxed and open. This is B.',ok:s=>!!s.finger_active?.thumb&&!s.menu_gesture?.pose,result:'B recognized.'},
 {title:'Start — Make the V sign',image:'v-sign.png',cue:'Extend index and middle fingers, close ring and pinky, then hold for a moment.',instant:true,menu:'start',ok:s=>s.menu_gesture?.pose==='start'&&s.menu_gesture?.recognized,result:'START recognized.'},
 {title:'Select — Give a thumbs-up',image:'thumbs-up.png',cue:'Extend your thumb and close all four fingers, then hold.',instant:true,menu:'select',ok:s=>s.menu_gesture?.pose==='select'&&s.menu_gesture?.recognized,result:'SELECT recognized.'},
 {title:'Glove Zap — push toward the camera',image:'push-toward-camera.png',instant:true,cue:'Move your open hand closer to the camera in one deliberate push.',ok:s=>s.push_gesture?.active,result:'Glove Zap recognized!'},
 {title:'Pull Back — away from the camera',image:'pull-away-from-camera.png',instant:true,cue:'Return to your calibrated starting position and distance, then move your open hand away from the camera. Keep your palm facing the camera and hold briefly. Return to your starting distance to release.',ok:s=>s.pull_gesture?.active,result:'Pull Back recognized!'},
 {title:'Roll wrist left',image:'wrist-roll-left.png',instant:true,cue:'Keep your hand centered and roll your wrist to the left.',ok:s=>s.recognition?.roll_left,result:'LEFT ROLL recognized.'},
 {title:'Roll wrist right',image:'wrist-roll-right.png',instant:true,cue:'Return to neutral, then roll your wrist to the right.',ok:s=>s.recognition?.roll_right,result:'RIGHT ROLL recognized.'},
 {title:'Close your hand',image:'close-all-fingers.png',cue:'Curl your thumb and all four fingers into a comfortable closed hand.',ok:s=>s.recognition?.closed_hand,result:'CLOSED HAND recognized.'},
 {title:'Menu guard — thumb and ring',image:'menu-guard.png',cue:'Curl only your thumb and ring finger. Keep index, middle, and pinky extended. This suppresses D-pad and buttons. Native Super Glove Ball positioning stays active; use Stop controller to reposition.',ok:s=>s.recognition?.menu_guard,result:'MENU GUARD recognized.'}
];
let playerReady=false;
let index=0,completed=new Set(),holdStarted=0,lastSequence=-1,latestSequence=-1,sequenceFloor=-1,advancing=false,practiceActive=false,advanceTimer=null,trainingComplete=false,lessonRevision=0,cameraRetryAt=0;
const practiceSession=(globalThis.crypto&&crypto.randomUUID)?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;
async function practice(enabled){const r=await fetch('/api/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:practiceSession,enabled}),keepalive:!enabled});if(!r.ok)throw new Error('Practice camera request failed.');practiceActive=enabled;return r}
function cameraMessage(message){const image=$('learn-camera'),panel=$('learn-startup');image.style.display='none';$('learn-camera-target').hidden=true;panel.style.display='flex';panel.textContent=message}
function syncPracticeCamera(s){const image=$('learn-camera'),starting=s.vision_state==='starting',ready=s.vision_state==='active'&&s.practice_mode;if(!ready){if(image.getAttribute('src'))image.removeAttribute('src');cameraMessage(starting?startupMessage(s):s.vision_state==='error'?'Camera unavailable. Check that it is connected; Glove Academy will retry automatically.':'Waiting for the practice camera…');return}if(!image.getAttribute('src')&&Date.now()>=cameraRetryAt){cameraRetryAt=Date.now()+1000;cameraMessage('Waiting for the camera image…');image.src=image.dataset.src+'?t='+Date.now()}}
async function startPractice(){try{await practice(true)}catch(e){cameraMessage('Could not start the practice camera. Glove Academy will keep trying.');$('lesson-result').textContent='Could not start the practice camera.';$('lesson-result').className='lesson-result'}}
function stopPractice(){if(!practiceActive)return;practiceActive=false;fetch('/api/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:practiceSession,enabled:false}),keepalive:true}).catch(()=>{})}
function action(s){if(s.recognition?.menu_guard)return 'MENU GUARD';if(s.recognition?.closed_hand)return 'CLOSED HAND';if(s.recognition?.roll_left)return 'ROLL LEFT';if(s.recognition?.roll_right)return 'ROLL RIGHT';if(s.pull_gesture?.active)return 'Pull Back';if(s.menu_gesture?.pose)return s.menu_gesture.pose.toUpperCase()+(s.menu_gesture.recognized?' recognized':' — hold');const d=Object.entries(s.dpad||{}).find(([,v])=>v);if(d)return d[0].toUpperCase();const b=Object.entries(s.buttons||{}).find(([,v])=>v);if(b)return b[0]==='glove_zap'?'Glove Zap':b[0].replace('_',' ').toUpperCase();const f=Object.entries(s.fingers||{}).filter(([,v])=>v>=2).map(([k])=>k);return f.length?f.join(' + '):'None'}
function drawHand(points){const canvas=$('hand-detail'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,300,220);if(points.length!==21)return;const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minX=Math.min(...xs),minY=Math.min(...ys),scale=Math.min(260/Math.max(.01,Math.max(...xs)-minX),180/Math.max(.01,Math.max(...ys)-minY)),pos=p=>[20+(p[0]-minX)*scale,20+(p[1]-minY)*scale];ctx.strokeStyle='#36dbe8';ctx.lineWidth=2;for(const chain of [[0,1,2,3,4],[0,5,6,7,8],[5,9,10,11,12],[9,13,14,15,16],[13,17,18,19,20],[0,17]]){ctx.beginPath();chain.forEach((id,i)=>{const p=pos(points[id]);i?ctx.lineTo(...p):ctx.moveTo(...p)});ctx.stroke()}ctx.fillStyle='#54e389';points.forEach(p=>{ctx.beginPath();ctx.arc(...pos(p),3,0,Math.PI*2);ctx.fill()})}
// Completion requires every lesson; skipping never earns the achievement.
function cancelLessonAdvance(){lessonRevision++;clearTimeout(advanceTimer);advanceTimer=null;advancing=false}
function beginTransition(){sequenceFloor=Math.max(sequenceFloor,latestSequence,lastSequence);cancelLessonAdvance();holdStarted=0;lastSequence=sequenceFloor}
function restartTraining(){if(window.resetAcademyProgress){return window.resetAcademyProgress()}beginTransition();index=0;completed.clear();trainingComplete=false;$('achievement').hidden=true;$('lesson-result').textContent='Show your hand to begin.';$('lesson-result').className='lesson-result';draw()}
function moveLesson(next){if(!playerReady)return;beginTransition();index=next;$('lesson-result').textContent='Lesson skipped.';$('lesson-result').className='lesson-result';draw();window.saveAcademyProgress?.()}
function finishLesson(revision){if(revision!==lessonRevision)return;advanceTimer=null;holdStarted=0;advancing=false;if(completed.size===lessons.length){beginTransition();trainingComplete=true;$('achievement').hidden=false;$('lesson-result').textContent='Training complete — achievement unlocked!';}else{let next=(index+1)%lessons.length;while(completed.has(next))next=(next+1)%lessons.length;beginTransition();index=next;}draw();window.saveAcademyProgress?.()}
function draw(s={}){$('lesson-content').hidden=trainingComplete;$('achievement').hidden=!trainingComplete;const lesson=lessons[index],panel=$('practice-lessons');panel.dataset.lesson=String(index+1);panel.dataset.complete=String(trainingComplete);panel.dataset.revision=String(lessonRevision);const menu=!!s.menu_gesture?.pose;const actions={'A':!!s.finger_active?.index&&!menu,'B':!!s.finger_active?.thumb&&!menu,'Glove Zap':!!s.push_gesture?.active,'Pull Back':!!s.pull_gesture?.active};$('practice-actions').innerHTML=Object.entries(actions).map(([label,active])=>`<span class="bit ${active?'on':''}">${label}</span>`).join('');$('lesson-image').src='/help-assets/gestures/actions/'+lesson.image;$('lesson-image').alt=lesson.title;$('finger-feedback').textContent='Curl / activation: '+Object.entries(s.finger_curls||{}).map(([name,value])=>`${name} ${Number(value).toFixed(3)} / ${Number(s.tuning?.effective?.[name]?.on??s.curl_threshold??0.5).toFixed(2)}`).join(' · ');const depth=lesson.image==='pull-away-from-camera.png'?s.pull_gesture:s.push_gesture;$('depth-feedback').textContent=depth?`${lesson.image==='pull-away-from-camera.png'?'Backward':'Forward'} movement: ${Math.max(0,Math.round(depth.depth*100))}% / ${Math.round(depth.threshold*100)}% required`:'';drawHand(s.hand_landmarks||[]);$('lesson-number').textContent=`Lesson ${index+1} of ${lessons.length}`;$('lesson-title').textContent=lesson.title;$('lesson-cue').textContent=lesson.cue;$('lesson-progress').innerHTML=lessons.map((_,i)=>`<i class="${completed.has(i)?'done':i===index?'current':''}"></i>`).join('');$('previous').disabled=trainingComplete||index===0;$('next').disabled=false;$('next').textContent=trainingComplete?'Start again':index===lessons.length-1?'Review lessons':'Skip lesson';$('tracking').textContent=s.detected?'Hand found':'No hand';$('recognized').textContent=action(s);$('confidence').textContent=`${Math.round((s.confidence||0)*100)}%`;}
async function update(){const requestRevision=lessonRevision;try{const s=await(await fetch('/status',{cache:'no-store'})).json();if(requestRevision!==lessonRevision)return;window.updateEasterEgg?.(s);const startup=startupMessage(s),starting=s.vision_state==='starting',ready=s.vision_state==='active'&&s.practice_mode;
const sequence=Number(s.sequence);if(Number.isFinite(sequence)){if(latestSequence>=0&&sequence<latestSequence){latestSequence=sequence;sequenceFloor=-1;lastSequence=-1}else latestSequence=Math.max(latestSequence,sequence)}
syncPracticeCamera(s);updateCalibration(s);
if(!playerReady||trainingComplete||document.getElementById('tune-switch')?.checked){draw(s);return}
if(!ready){holdStarted=0;$('lesson-result').textContent=s.vision_state==='error'?(s.vision_error||'Vision unavailable; retrying.'):startup||'Starting practice camera…';$('lesson-result').className='lesson-result';$('tracking').textContent=starting?'Starting…':'Waiting';$('recognized').textContent='None';$('confidence').textContent='—';return}
if(!Number.isFinite(sequence)||sequence<=sequenceFloor||sequence===lastSequence)return;lastSequence=sequence;const passed=lessons[index].ok(s),box=$('lesson-result');if(passed){if(!holdStarted)holdStarted=Date.now();const remaining=lessons[index].instant?0:Math.max(0,600-(Date.now()-holdStarted));box.textContent=remaining?`Hold it… ${Math.ceil(remaining/100)/10}s`:lessons[index].result;box.className='lesson-result ready';if(!remaining&&!advancing){completed.add(index);window.saveAcademyProgress?.();advancing=true;draw(s);const advanceRevision=lessonRevision;advanceTimer=setTimeout(()=>finishLesson(advanceRevision),700)}}else if(!advancing){holdStarted=0;box.textContent=s.worker_running?(s.detected?(lessons[index].menu?(s.menu_gesture?.pose===lessons[index].menu?'Pose found — keep holding…':'Match the hand image. Keep your palm near center; check which fingers read closed.'):'Try the gesture shown above.'):'Show your hand to begin.'):(s.camera_available?'Gesture tracker is starting…':'Camera is offline.');box.className='lesson-result';}draw(s)}catch(e){if(requestRevision!==lessonRevision)return;cameraMessage('Camera status unavailable. Reconnecting…');$('lesson-result').textContent='Waiting for the gesture tracker…';$('lesson-result').className='lesson-result'}}
$('restart-training').onclick=restartTraining;$('previous').onclick=()=>moveLesson(Math.max(0,index-1));$('next').onclick=()=>{if(trainingComplete)return restartTraining();else moveLesson((index+1)%lessons.length)};$('center').onclick=calibrate;
$('learn-camera').onload=()=>{$('learn-camera').style.display='block';$('learn-camera-target').hidden=false;$('learn-startup').style.display='none'};$('learn-camera').onerror=()=>{cameraRetryAt=Date.now()+1000;$('learn-camera').removeAttribute('src');cameraMessage('Camera image unavailable. Reconnecting…')};
window.addEventListener('pagehide',stopPractice);draw();startPractice();setInterval(()=>{if(practiceActive)practice(true).catch(()=>{})},2000);setInterval(update,75);update();""",
)


# Keep the camera beside the active lesson or tuning controls.
_tune_intro, _tune_body = TUNE_CONTENT.split('<div id=tune-panel hidden>', 1)
LEARN = LEARN.replace(b'<section class=card>', b'<section class=card id=practice-lessons>', 1)
LEARN = LEARN.replace(b'<div class=learn-grid>', (_tune_intro + '</section>').encode() + b'<div class=learn-grid>', 1)
LEARN = LEARN.replace(b'<section class=card id=practice-lessons>',
    ('<section class=card id=tune-panel hidden>' + _tune_body[:-len('</div></section>')] + '</section>').encode()
    + b'<section class=card id=practice-lessons>', 1)
LEARN = LEARN.replace('<div class=practice-badge>● PRACTICE ONLY</div></div>'.encode(), '<div class=practice-badge>● PRACTICE ONLY</div>'.encode() + TUNE_THRESHOLDS.encode() + b'</div>', 1)
LEARN = LEARN.replace(b'</body>', b'<script>' + TUNE_SCRIPT.encode() + b'</script></body>')
LEARN = LEARN.replace((_tune_intro + '</section>').encode(), PLAYER_SELECTOR_CONTENT.encode() + (_tune_intro + '</section>').encode(), 1)
LEARN = LEARN.replace(b'</body>', b'<script>' + PLAYER_SCRIPT.encode() + b'</script></body>')
