# Project: VirtualGlove
# File: src/powerglove_vision/dashboard_web.py
# Purpose: Render Dashboard controls and live controller status.
# Author: Iain Bennett
# Copyright (c) 2026 Iain Bennett
# SPDX-License-Identifier: MIT
# Full history: docs/CHANGELOG.md and Git history.
# Change log:
#   2026-09-10 - Show the selected profile's play card when statistics are hidden.
#   2026-09-07 - Request detailed worker telemetry only while statistics are shown.
#   2026-09-07 - Identified the active native X/Y coordinate source.
#   2026-09-06 - Add opt-in independent native hand movement tracking.
#   2026-09-06 - Separate maintained web modules without changing rendered pages.

"""Render Dashboard controls and live controller status."""

from .statistics_web import STATISTICS_SCRIPT, STATISTICS_SWITCH
from .web_common import _page, _profile_options, VISION_STARTUP_SCRIPT

DASHBOARD = _page(
    "Dashboard",
    """<h1>I love the Power Glove. It’s so bad.</h1><p class='lead dashboard-lead'>Live vision, gesture and controller diagnostics from your camera-only VirtualGlove.</p>
<p><a class=button href=/ready>Get ready to play</a></p>
<div class=status-grid>
 <div class=card><div class=label>System</div><div class=value id=system>Starting</div></div>
 <div class=card><label class=label for=player-select>Player</label><select class=profile-select id=player-select disabled></select><div class=label id=player-notice role=status aria-live=polite style='margin-top:6px'></div></div>
 <div class=card><label class=label for=profile-selector>Active profile</label><select class=profile-select id=profile-selector>""" + _profile_options() + """</select><div class=label id=profile-source style='margin-top:6px'>—</div></div>
 <div class=card><div class=label>Game</div><div class=value id=game>—</div><div class=label id=game-session style='margin-top:6px'>Starting</div></div>
 <div class=card><div class=label>Hand tracking</div><div class=value id=tracking>—</div><div class=meter><i id=confidence></i></div></div>
 <div class=card><div class=label>Controller delivery</div><div class=value id=receiver>Starting</div></div>
</div>
<div class=controls>""" + STATISTICS_SWITCH + """</div>
<div class='dashboard-workspace statistics-off' id=dashboard-workspace><div><div class=camera-stage><img class=camera id=camera data-src=/stream alt='Live camera view'><div class=camera-centre-target id=camera-centre-target hidden aria-hidden=true></div><div class=camera-idle id=camera-idle role=status>VIRTUALGLOVE<small>Gestures are paused. Select a profile to resume.</small></div></div>
<div class='controls dashboard-controls'><button id=center>Center hand</button><button id=controller-toggle>Start controller</button><a class=button href=/setup>Connection</a><button class=danger id=shutdown-system>Shutdown</button></div><p id=center-guidance role=status></p><div class=notice id=dashboard-notice role=status aria-live=polite></div></div>
<div class=diagnostic-grid id=dashboard-statistics hidden>
 <section class=card><h2>Controller output</h2><div class=label>Directions</div><div class=bits id=dpad></div><div class=label style='margin-top:14px'>Buttons</div><div class=bits id=buttons></div></section>
 <section class=card><h2>Axes</h2><div id=axes></div></section>
 <section class=card><h2>Finger curl</h2><div id=fingers></div></section>
 <section class=card><h2>Performance</h2><div id=performance>Waiting for samples…</div></section>
 <section class='card events-card'><h2>Recent events</h2><div class=events id=events><div>Waiting for tracker…</div></div></section>
</div>
<section class='card program-card' id=dashboard-program aria-live=polite>
 <div class=label>Current program</div><h2 id=program-title>Gestures off — no active profile</h2><p class=program-purpose id=program-purpose>Camera gesture controls are paused; the physical Player 1 controller remains available.</p>
 <p class=program-summary id=program-summary>Select a profile above or start a registered game on RetroPie.</p><p class=program-purpose id=program-feedback hidden role=status aria-live=polite></p><ul class=program-mappings id=program-mappings></ul>
 <a class=program-help href=/help/gameplay>Open the Gameplay Guide</a>
</section></div>""",
    STATISTICS_SCRIPT + VISION_STARTUP_SCRIPT + r"""const $=id=>document.getElementById(id);
function buttonText(b,text){if(b.textContent!==text)b.textContent=text;}
let controllerBusy=false;
let calibrationPending=false,calibrationSeen=false,calibrationStarted=0,calibrationDoneUntil=0;
function updateCalibration(s){const b=$('center');if(s.calibrating){calibrationSeen=true;calibrationPending=true;if(!calibrationStarted)calibrationStarted=Date.now()}
if(calibrationPending&&calibrationSeen&&s.calibrated&&!s.calibrating){calibrationPending=false;calibrationSeen=false;calibrationStarted=0;calibrationDoneUntil=Date.now()+1800}
if(calibrationPending&&Date.now()-calibrationStarted>20000){calibrationPending=false;calibrationSeen=false;calibrationStarted=0;b.title='Calibration did not finish. Show a relaxed hand and try again.'}
b.disabled=s.vision_state!=='active'||calibrationPending;b.classList.toggle('danger',calibrationPending);b.setAttribute('aria-busy',String(calibrationPending));buttonText(b,calibrationPending?'Centering…':Date.now()<calibrationDoneUntil?'Center saved ✓':'Center hand');}
async function calibrate(){if(calibrationPending)return;calibrationPending=true;calibrationSeen=false;calibrationStarted=Date.now();calibrationDoneUntil=0;updateCalibration({vision_state:'active'});try{const r=await fetch('/calibrate',{method:'POST'});if(!r.ok)throw Error('Centering request failed');}catch(e){calibrationPending=false;calibrationStarted=0;updateCalibration({vision_state:'active'});$('center').textContent='Try setting center again';$('center').title=e.message}}

const bits=(id,obj)=>{$(id).innerHTML=Object.entries(obj||{}).map(([k,v])=>`<span class="bit ${v?'on':''}">${k.toUpperCase()}</span>`).join('')||'<span class=bit>None</span>'};
const bars=(id,obj,max=32767)=>{$(id).innerHTML=Object.entries(obj||{}).map(([k,v])=>`<div class=label>${k}: ${v}</div><div class=meter><i style="width:${Math.min(100,Math.abs(v)/max*100)}%"></i></div>`).join('')||'—'};
const performance=s=>{const p=s.performance||{},inference=p.inference_ms||{},age=p.capture_age_ms||{},sample=p.sample_age_ms||{},transition=p.controller_transition_age_ms||{},source=s.native_xy_source==='mediapipe'?'MediaPipe — Latest coordinate':'Inactive';return [`Model: ${s.tracker_backend_label||s.tracker_backend||'—'}`,`Native X/Y: ${source}`,`Inference: ${s.inference_hz??'—'} Hz`,`Inference p50 / p95: ${inference.p50??'—'} / ${inference.p95??'—'} ms`,`Camera read → send p50 / p95: ${sample.p50??'—'} / ${sample.p95??'—'} ms`,`Changed control → send p50 / p95: ${transition.p50??'—'} / ${transition.p95??'—'} ms`,`Frame waiting before inference p50 / p95: ${age.p50??'—'} / ${age.p95??'—'} ms`,`Superseded camera frames: ${s.capture_skipped_total??0}`,`Preview encode: ${s.preview_encode_ms??'—'} ms`].map(x=>`<div class=label style="margin:5px 0">${x}</div>`).join('')};
const programDetails={
 program_1:{title:'Program 1 — General side view',purpose:'The original all-purpose Power Glove program.',summary:'Hand position moves in four directions; finger curls operate A and B, with a turnaround attack.',mappings:[['Move hand','D-pad'],['Curl thumb','Rapid A'],['Curl index','Rapid B'],['Curl last three fingers','Turn and fire B']]},
 program_2:{title:'Program 2 — Centering coach',purpose:'General controls with live centering feedback.',summary:'The original glove beep is replaced by a visual centered indicator.',mappings:[['Move hand','D-pad'],['Curl thumb','Rapid A'],['Curl index','Rapid B'],['Curl last three fingers','Turn and fire B']]},
 program_3:{title:'Program 3 — Top view',purpose:'Tabletop-style movement for overhead games.',summary:'Push and pull for vertical movement, with sideways hand movement for steering. Gauntlet can use this as an alternative although Mattel indexed it under Program 1.',mappings:[['Push / pull','Up / Down'],['Move left / right','Left / Right'],['Curl thumb / index','Rapid A / B']]},
 program_4:{title:'Program 4 — Iron Tank',purpose:'Finger poses behave like tank-tread controls.',summary:'Distinct open and curled finger combinations drive direction; wrist twists produce diagonal commands.',mappings:[['Open / close four fingers','Up / Down'],['Index open / last three curled','Right'],['Index curled / last three open','Left'],['Curl thumb','Rapid A'],['Turn wrist upright','Rapid B'],['Twist wrist','Up + Left / Right']]},
 program_5:{title:'Program 5 — Flight',purpose:'Bank and fly with depth and wrist movement.',summary:'Designed for aerial-view games including Alpha Mission, Life Force, Xevious and 1943.',mappings:[['Push / pull','Up / Down'],['Move or bank sideways','Left / Right'],['Curl thumb / index','Rapid A / B']]},
 program_6:{title:'Program 6 — Double Dragon',purpose:'Movement and compound fighting actions.',summary:'Combines finger and wrist poses into attacks that normally require multiple controls.',mappings:[['Move / push / pull','D-pad'],['Curl index','Rapid A'],['Curl thumb','Rapid B'],['Curl last three','Rapid A + B / jump'],['Fist forward','Hold Up / climb'],['Twist clockwise','Fast turn twice']]},
 program_7:{title:'Program 7 — Punch-Out!!',purpose:'Boxing punches, dodges and blocks.',summary:'Use an open hand to dodge, a forward fist to punch, and wrist rotation to block.',mappings:[['Open hand + move','Dodge / duck'],['Fist + punch','Left / right body punch'],['High fist + punch','Left / right head punch'],['Rotate wrist','Block'],['Fist + pull back','Star punch'],['Thumb curl','Rapid A']]},
 program_8:{title:'Program 8 — Baseball',purpose:'Baseball-diamond movement and actions.',summary:'The game state determines whether the same controls field, bat or run.',mappings:[['Move around diamond','Bases / fielding'],['Curl thumb','Swing or run back'],['Curl index / roll wrist','Throw or run']]},
 program_9:{title:'Program 9 — Rad Racer',purpose:'Steering-wheel driving without rapid fire.',summary:'Make a fist once to ready the program, then steer and operate turbo, throttle and brake.',mappings:[['Make fist','Ready / A'],['Rotate wrist','Steer'],['Fist forward','Turbo'],['Raise open hand','Down'],['Lower fist','B']]},
 program_10:{title:'Program 10 — R.C. Pro-Am',purpose:'Finger steering with automatic throttle.',summary:'B stays held automatically for throttle; lower your hand to release it.',mappings:[['Curl index','Left'],['Curl last three','Right'],['Curl thumb','Rapid A'],['Hand centered / hand lowered','Hold B / release B']]},
 program_11:{title:'Program 11 — Fast turn',purpose:'Program 1 controls with a spinning attack.',summary:'The last-three-finger pose alternates direction while firing B.',mappings:[['Move hand','D-pad'],['Curl thumb / index','Rapid A / B'],['Curl last three','Fast turn + B']]},
 program_12:{title:'Program 12 — Super Mario Bros.',purpose:'Standard movement with fast and slow running.',summary:'Middle and last-three-finger poses modify horizontal movement speed.',mappings:[['Move hand','D-pad'],['Curl thumb / index','Rapid A / B'],['Curl middle','B + horizontal movement'],['Curl last three','Slow horizontal movement']]},
 program_13:{title:'Program 13 — Finger buttons',purpose:'Gesture buttons with manual movement.',summary:'VirtualGlove supplies A and B; use a conventional controller for directions and menus.',mappings:[['Curl thumb','Rapid A'],['Curl index','Rapid B'],['Conventional controller','D-pad / menus']]},
 program_14:{title:'Program 14 — Physical controller only',purpose:'Camera gestures are completely paused.',summary:'Use the merged physical Player 1 controller for all input while VirtualGlove retains the selected game profile.',mappings:[['Physical Player 1 controller','All controls']]},
 bad_street_brawler:{title:'Bad Street Brawler',purpose:'VirtualGlove moves tuned for the cartridge.',summary:'Hand position handles movement. Wrist rolls, finger curls and a forward Glove Zap provide the fighting actions.',mappings:[['Move hand','Eight-direction movement'],['Roll wrist','Left or right attack'],['Curl middle finger','A + B attack'],['Curl thumb','Turbo B'],['Glove Zap','Power punch']]},
 super_glove_ball:{title:'Super Glove Ball',purpose:'Continuous Robo-Glove control with a joystick fallback.',summary:'The custom Nestopia core follows your hand continuously. Other NES cores use the same profile as an eight-direction joystick.',mappings:[['Move hand','Continuous X/Y or D-pad'],['Curl index','A'],['Curl thumb','B'],['Close hand','Grab / close Robo-Glove'],['Point index','Robo-Bullet']]},
 off:{title:'Gestures off — no active profile',purpose:'Camera gesture controls are paused.',summary:'The physical Player 1 controller still works. Select a VirtualGlove profile above or start a registered game on RetroPie.',mappings:[['Physical Player 1 controller','Still available']]},
 program_a:{title:'Program A — Pinball',purpose:'Independent flippers with wrist tilt.',summary:'Designed for pinball tables and games that benefit from two separate finger actions.',mappings:[['Curl index','A / right flipper'],['Curl thumb','Up / left flipper'],['Roll wrist','B / tilt'],['Pull Back','Toggle combined flippers']]},
 program_b:{title:'Program B — Joust',purpose:'Position steering with rhythmic flap input.',summary:'Move horizontally to steer, then curl a finger for a pulsed flap.',mappings:[['Move left / right','Steer'],['Curl index or middle','Turbo A / flap'],['Curl thumb','B']]},
 program_c:{title:'Program C — Gyruss',purpose:'Wrist rotation, continuous fire and bombs.',summary:'Roll your wrist around the playfield, keep the index finger straight to fire and Pull Back for a bomb.',mappings:[['Roll wrist','Rotate left / right'],['Keep index straight','A / fire'],['Pull Back','B / bomb']]},
 program_d:{title:'Program D — Challenge',purpose:'A mirror-world control challenge.',summary:'Hand movement is reversed while the thumb and index finger operate the action buttons.',mappings:[['Move hand','Reversed directions'],['Curl thumb','A'],['Curl index','B']]},
 program_e:{title:'Program E — Defender II',purpose:'Ship movement with fire and evasive actions.',summary:'Position moves the ship, while finger and wrist gestures handle its weapons.',mappings:[['Move hand','Eight-direction movement'],['Curl thumb','A / fire'],['Roll wrist','B / smart bomb'],['Curl ring finger','Rapid evasive movement']]},
 program_f:{title:'Program F — Sesame Street',purpose:'Simple open-hand Yes and closed-hand No.',summary:'A friendly two-choice program for simple games and younger players.',mappings:[['Move open hand','A / Yes'],['Close hand','B / No']]},
 program_g:{title:'Program G — Gun Smoke',purpose:'Move and fire with natural hand gestures.',summary:'Hand position controls walking. Index curl and forward push provide the two firing actions.',mappings:[['Move hand','Eight-direction movement'],['Curl index','A / fire'],['Glove Zap','B / fire'],['Roll wrist','Add left / right movement']]},
 program_h:{title:'Program H — General',purpose:'Familiar controls for learning and general play.',summary:'A useful starting point for an unmapped game, with ordinary movement and pulsed action buttons.',mappings:[['Move hand','Eight-direction movement'],['Curl index','Turbo A'],['Curl thumb','Turbo B']]},
 program_i:{title:'Program I — Knight Rider',purpose:'Wrist steering, throttle, brake and turbo.',summary:'A driving layout that moves steering to the wrist and speed controls to hand gestures.',mappings:[['Roll wrist','Steer left / right'],['Curl index','Up / throttle'],['Move down','Down / brake'],['Glove Zap','Up + A / turbo'],['Curl thumb','B']]}
};
let displayedProgram='';
function displayProgram(profile){if(profile===displayedProgram)return;displayedProgram=profile;const p=programDetails[profile]||{title:profile||'Unknown profile',purpose:'Custom controller profile',summary:'See the Gameplay Guide for this profile’s controls.',mappings:[]};$('program-title').textContent=p.title;$('program-purpose').textContent=p.purpose;$('program-summary').textContent=p.summary;const rows=p.mappings.map(([gesture,result])=>{const row=document.createElement('li'),strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=gesture;span.textContent=result;row.append(strong,span);return row});$('program-mappings').replaceChildren(...rows)}
function displayProgramFeedback(s){const el=$('program-feedback'),p=s.program_feedback||{};if((s.active_profile||s.configured_profile)==='program_2'){el.hidden=false;el.textContent=p.centered===true?'Centered':p.centered===false?'Return to centre':'Centering feedback unavailable';}else if((s.active_profile||s.configured_profile)==='program_9'&&p.ready===false){el.hidden=false;el.textContent='Make a fist once to ready Program 9.';}else{el.hidden=true;el.textContent=''}}
let seen=[],switching=false,desiredProfile='',cameraImageReady=false;
$('camera').onload=()=>{cameraImageReady=true;$('camera-centre-target').hidden=false};
$('camera').onerror=()=>{cameraImageReady=false;$('camera-centre-target').hidden=true;$('camera').removeAttribute('src')};
function displayStatistics(){const enabled=window.dashboardStatisticsEnabled();$('dashboard-statistics').hidden=!enabled;$('dashboard-program').hidden=enabled;if(!enabled){seen=[];for(const id of ['dpad','buttons','axes','fingers','performance','events'])$(id).textContent='';}}
window.addEventListener('statisticschange',displayStatistics);displayStatistics();
async function update(){if(document.hidden)return;try{const statusPath=window.dashboardStatisticsEnabled()?'/status?statistics=1':'/status',s=await(await fetch(statusPath,{cache:'no-store'})).json();window.updateEasterEgg?.(s);const active=s.active_profile||s.configured_profile,idle=s.vision_state==='idle'||active==='off',starting=s.vision_state==='starting',ready=s.vision_state==='active',startup=startupMessage(s);
$('system').textContent=idle?'Gestures idle':(s.vision_state==='error'?(s.vision_error||'Vision unavailable'):(s.vision_state==='starting'?'Starting vision':s.worker_running?(s.detected?'Tracking':'Ready'):(s.camera_available?'Starting tracker':'Camera not found'))); $('system').className='value '+(s.vision_state==='error'?'bad':(idle||ready?'good':'warn'));
if(switching&&active===desiredProfile){switching=false;$('profile-selector').disabled=false}if(!switching)$('profile-selector').value=active;$('profile-source').textContent=s.profile_source||'Startup'; $('game').textContent=s.game||'Startup default';
$('dashboard-program').dataset.profile=active;displayProgram(active);
displayProgramFeedback(s);
$('game-session').textContent=s.game_session_active?'Registered game active':(s.profile_source==='Dashboard'?'Manual profile':'No registered game');$('game-session').className='label '+(s.game_session_active?'good':'');
$('camera').style.display=idle||starting?'none':'block';$('camera-idle').style.display=idle||starting?'flex':'none';$('camera-idle').textContent=starting?startup:(active==='program_14'?'PROGRAM 14 — Use a conventional controller.':'VIRTUALGLOVE — Gestures are paused. Select a profile to resume.');if(idle||starting){cameraImageReady=false;$('camera-centre-target').hidden=true;$('camera').removeAttribute('src')}else if(!$('camera').getAttribute('src')){cameraImageReady=false;$('camera-centre-target').hidden=true;$('camera').src=$('camera').dataset.src+'?t='+Date.now()}else $('camera-centre-target').hidden=!cameraImageReady;updateCalibration(s);
$('receiver').textContent=!s.connection_configured?'Set up Connection':s.controller_request_pending?'Waiting for tracker':s.controller_enabled?(!s.controller_context_active?'Armed — waiting for game':starting?'Waiting for vision':idle?(active==='program_14'?'Paused — manual controls':'Ready when gestures resume'):(s.launch_guard_active?'Launch delay':(s.receiver_available===true?'Sending controls':'Waiting for console'))):'Stopped'; $('receiver').className='value '+(s.receiver_available===true||idle||s.controller_enabled&&!s.controller_context_active?'good':'warn');
buttonText($('controller-toggle'),controllerBusy?'Please wait…':s.controller_enabled?'Stop controller':'Start controller'); $('controller-toggle').className=s.controller_enabled?'danger':''; $('controller-toggle').dataset.enabled=s.controller_enabled?'true':'false'; $('controller-toggle').disabled=controllerBusy||!s.connection_configured; $('controller-toggle').title=s.connection_configured?'':'Configure your RetroPie destination in Connection first';
const player=s.player||{},selected=(player.players||[]).find(p=>p.id===player.active);$('center-guidance').textContent=player.needs_center?`Center your hand for ${selected?selected.name:'the selected player'} before starting controls. Hold a relaxed open hand at your normal playing position and select the centering button.`:'';
$('tracking').textContent=starting?'Starting…':idle?'Paused':(s.calibrating?'Centering — hold still':(s.detected?`${Math.round((s.confidence||0)*100)}% confidence`:'Show your hand')); $('confidence').style.width=`${Math.round((s.confidence||0)*100)}%`;
if(window.dashboardStatisticsEnabled()&&!document.hidden){bits('dpad',s.dpad);bits('buttons',s.buttons);bars('axes',s.axes);bars('fingers',s.fingers,2);$('performance').innerHTML=performance(s);
for(const event of (s.events||[])) seen.unshift(`${new Date().toLocaleTimeString()}  ${event}`);seen=seen.slice(0,30);if(seen.length){const rows=seen.map(text=>{const row=document.createElement('div');row.textContent=text;return row});$('events').replaceChildren(...rows);}}
}catch(e){$('system').textContent='Dashboard disconnected';$('system').className='value bad'}}
fetch('/api/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:false,reset:true})}).finally(update);setInterval(update,250);
$('center').onclick=calibrate;
$('profile-selector').onchange=async()=>{const p=$('profile-selector'),notice=$('dashboard-notice');desiredProfile=p.value;switching=true;p.disabled=true;notice.textContent='Switching profile…';try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:desiredProfile})}),x=await r.json();if(!r.ok)throw new Error(x.error||'Could not change profile.');notice.textContent=desiredProfile==='off'?'Gestures paused. Camera capture is stopping.':'Profile selected.';}catch(e){switching=false;p.disabled=false;notice.textContent=e.message;update()}};
$('controller-toggle').onclick=async()=>{if(controllerBusy)return;controllerBusy=true;const b=$('controller-toggle'),enabled=b.dataset.enabled!=='true';b.disabled=true;try{const r=await fetch('/api/controller',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})}),x=await r.json();if(!r.ok)throw Error(x.error||'Could not change controller state.');$('dashboard-notice').textContent=x.pending?'Request saved. Waiting for the tracker; the Controller will retry.':enabled?'Controller armed.':'Stop request delivered to tracking.';}catch(e){$('dashboard-notice').textContent=e.message;}finally{controllerBusy=false;b.disabled=false;update();}};
$('shutdown-system').onclick=()=>shutdownSystem($('shutdown-system'));
async function shutdownSystem(button){if(!confirm('Request a system halt? Controller input will stop. Some UNO Q boards restart automatically after shutdown. A disconnected website does not confirm it is safe to remove power.'))return;button.disabled=true;button.textContent='Shutting down…';try{const r=await fetch('/api/system/shutdown',{method:'POST',headers:{'Content-Type':'application/json','X-VirtualGlove-Action':'shutdown'},body:JSON.stringify({confirm:'SHUTDOWN'})}),x=await r.json();if(!r.ok)throw new Error(x.error||'Shutdown request failed.');$('system').textContent='Shutting down safely';$('system').className='value warn';}catch(e){button.disabled=false;button.textContent='Shutdown';alert(e.message);}}""",
)


from .player_web import PLAYER_SCRIPT

DASHBOARD = DASHBOARD.replace(b"</body>", b"<script>" + PLAYER_SCRIPT.encode() + b"</script></body>")
