# Project: VirtualGlove
# File: src/powerglove_vision/tuning_web.py
# Purpose: Render the guided hand-personalization wizard.
# Author: Iain Bennett
# Copyright (c) 2026 Iain Bennett
# SPDX-License-Identifier: MIT
# Full history: docs/CHANGELOG.md and Git history.
# Change log:
#   2026-09-10 - Use Pixel Pal's coaching pose in guided personalization.
#   2026-09-06 - Separate maintained web modules without changing rendered pages.

"""Render the guided hand-personalization wizard."""

TUNE_CONTENT = """<style>
#tune-switch{appearance:none;width:42px;height:24px;display:inline-block;vertical-align:middle;border-radius:14px;background:#303748;position:relative;margin:0 10px 0 0;cursor:pointer;padding:0}#tune-switch::before{content:"";position:absolute;width:18px;height:18px;left:2px;top:2px;border-radius:50%;background:white;transition:transform .15s}#tune-switch:checked{background:#3d75ff}#tune-switch:checked::before{transform:translateX(18px)}
.tune-mode-bar{display:flex;align-items:center;gap:16px;margin:12px 0;padding:12px 16px}.tune-mode-bar>label{display:flex;align-items:center;flex-shrink:0;margin:0}.tune-mode-bar>p{margin:0;color:var(--muted);font-size:13px}.pal-coach{display:grid;grid-template-columns:82px 1fr;gap:12px;align-items:center;padding:10px;border:1px solid var(--line);border-radius:12px;background:#090b11}.pal-coach img{width:76px;height:86px;object-fit:contain}.wizard-step{color:var(--cyan);font-size:12px;letter-spacing:1px;text-transform:uppercase}.problem-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:14px 0}.problem-grid button{text-align:left;min-height:58px}.wizard-screen{margin-top:14px}.wizard-primary{width:100%;font-size:17px;margin-top:9px}.wizard-progress{height:9px;background:#303748;border-radius:9px;overflow:hidden}.wizard-progress i{display:block;height:100%;background:var(--cyan)}.ready-good{color:var(--green)}.ready-warn,.quality-warning{color:#ffd166}.wizard-nav{display:flex;gap:8px;margin-top:14px}.advanced-tuning{margin-top:15px}.advanced-tuning summary{cursor:pointer;font-weight:700}.reach-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:12px 0}.reach-grid label{display:grid;gap:4px}.reach-grid input{width:100%;padding:7px}#tune-thresholds table{width:100%;table-layout:fixed;border-collapse:collapse;font-size:13px}#tune-thresholds th,#tune-thresholds td{padding:5px 8px;text-align:left;border-bottom:1px solid var(--line)}#tune-thresholds input{width:100%;max-width:100px;padding:6px}.diagnostic-card{margin-top:14px;padding:12px;border:1px solid var(--line);border-radius:9px}
@media(max-width:900px){.tune-mode-bar{flex-wrap:wrap}.problem-grid{grid-template-columns:1fr}.learn-grid:has(#tune-panel:not([hidden])){display:flex;flex-direction:column}.learn-grid:has(#tune-panel:not([hidden]))>.learn-camera{order:2;width:100%}#tune-panel{order:1;width:100%}}
</style><section class="card tune-mode-bar"><label><input id=tune-switch type=checkbox role=switch> Tune gestures</label><p>Personalize recognition for your hand. Controller output stays paused.</p><div id=tune-panel hidden>
<div class=pal-coach><img src="/help-assets/gestures/v2/pixel-pal-coach.png" alt="Pixel Pal points toward the next personalization step"><div><div class=wizard-step id=tune-step>Personalize recognition</div><p id=tune-coach>What would you like help with?</p></div></div>
<div id=tune-problems class="problem-grid wizard-screen"><button id=problem-setup data-problem=setup>Set up a new hand</button><button id=problem-difficult data-problem=difficult>A gesture is hard to trigger</button><button id=problem-accidental data-problem=accidental>A gesture happens accidentally</button><button id=problem-off-center data-problem=off_center>Movement feels off-center</button></div>
<div id=tune-gesture-step class=wizard-screen hidden><label for=tune-gesture>Which gesture?</label><select id=tune-gesture></select><button class="wizard-primary" id=tune-choose>Continue</button></div>
<div id=tune-center-step class=wizard-screen hidden><p>Hold a relaxed open palm at the comfortable center of your play area. Your saved center changes only when you ask.</p><button class=wizard-primary id=tune-calibrate>Center hand</button><button class=wizard-primary id=tune-center-done>My center already looks right</button></div>
<div id=tune-record-step class=wizard-screen hidden><p id=tune-components></p><p id=tune-instruction></p><p id=tune-readiness role=status aria-live=polite></p><p id=tune-quality class=quality-warning></p><div class=wizard-progress><i id=tune-bar></i></div><button class=wizard-primary id=tune-record>I'm ready</button><button class=wizard-primary id=tune-suggest hidden>Analyze my movement</button><p id=tune-progress role=status aria-live=polite></p><p id=tune-fingers role=status aria-live=polite></p></div>
<div id=tune-test-step class=wizard-screen hidden><p>Try the gesture twice, returning to a relaxed hand after each use.</p><p id=tune-test-progress role=status aria-live=polite></p><button class=wizard-primary id=tune-test>Start the try-it test</button><button class=wizard-primary id=tune-save disabled>Save my personalization</button></div>
<div id=tune-done class=wizard-screen hidden><h3>Personalization saved</h3><p>Pixel Pal applied this adjustment across every game profile. Your other settings stayed unchanged.</p><button class=wizard-primary id=tune-again>Personalize something else</button></div>
<div class=wizard-nav><button id=tune-back>Back</button><button id=tune-discard>Cancel</button></div><p id=tune-notice role=status aria-live=polite></p>
<details class=advanced-tuning><summary>Movement reach</summary><p>These are normalized distances from your saved center. Smaller values require less hand travel. Saving here changes only reach.</p><div class=reach-grid><label>Left reach<input id=reach-left type=number min=.05 step=.000001></label><label>Right reach<input id=reach-right type=number min=.05 step=.000001></label><label>Up reach<input id=reach-up type=number min=.05 step=.000001></label><label>Down reach<input id=reach-down type=number min=.05 step=.000001></label></div><p id=reach-summary></p><button id=reach-save>Save reach values</button><button id=reach-reset>Restore full camera field</button><p id=reach-notice role=status aria-live=polite></p></details>
<details class=advanced-tuning><summary>Advanced thresholds and diagnostics</summary><p>Optional expert controls. Activation starts a gesture; the lower release value stops it.</p><div id=tune-thresholds><p id=tune-live></p><table><thead><tr><th>Gesture</th><th>Activation</th><th>Release</th></tr></thead><tbody id=tune-fields></tbody></table><button id=tune-preview>Preview numbers</button><button id=tune-reset>Restore selected defaults</button></div><div class=diagnostic-card><h3>Diagnostic capture</h3><p>A temporary local video checks visibility, recognition, timing, and lighting. It is deleted after analysis; the report contains no images.</p><button id=diagnostic-start>Start diagnostic</button><button id=diagnostic-record hidden>Record this step</button><button id=diagnostic-cancel hidden>Cancel diagnostic</button><button id=diagnostic-download hidden>Download report</button><p id=diagnostic-status></p></div></details>
</div></section>"""

TUNE_THRESHOLDS = ""

TUNE_SCRIPT = r"""(()=>{
const el=id=>document.getElementById(id);let enabled=false,busy=false,last=null,polling=false,counting=false,fieldsKey='',reachKey='',reachDirty=false;
async function api(action,extra={}){const r=await fetch('/api/tuning',{method:'POST',headers:{'Content-Type':'application/json','X-VirtualGlove-Action':'tuning'},body:JSON.stringify({action,session:practiceSession,...(window.playerIdentity?.()||{}),...extra})});const x=await r.json();if(!r.ok)throw Error(x.error||'Personalization request failed');return x}
function show(id,on){el(id).hidden=!on}function pairs(){const out={};el('tune-fields').querySelectorAll('[data-channel]').forEach(row=>{const a=row.querySelectorAll('input');if(row.dataset.changed||last?.preview?.[row.dataset.channel])out[row.dataset.channel]={on:Number(a[0].value),off:Number(a[1].value)}});return out}
const featured=['start','select','thumb','index','middle','ring','pinky','push','pull','closed_hand','menu_guard'];
const motion={left:'Move your open hand left and hold.',right:'Move your open hand right and hold.',up:'Move your open hand up and hold.',down:'Move your open hand down and hold.',roll_left:'Roll your wrist left and hold.',roll_right:'Roll your wrist right and hold.',push:'Push toward the camera and return. Repeat three times.',pull:'Move away from the camera and return. Repeat three times.'};
function instruction(s){const phase=s.completed_phases;if(phase>=3)return'Recording complete. Analyze the measurements, then try the adjustment.';if(phase===1)return motion[s.gesture]||(s.mode==='hand_setup'?'Make a gentle fist with your thumb outside your fingers.':'Make '+s.gestures[s.gesture]+'.');if(phase===2)return'Return to a relaxed open hand at your starting position.';return motion[s.gesture]?'Hold a relaxed open hand at your starting position.':'Show a comfortable open hand. Do not stretch your fingers.'}
function populate(s){if(el('tune-gesture').options.length)return;for(const [label,keys] of [['Common adjustments',featured],['More adjustments',Object.keys(s.gestures).filter(k=>!featured.includes(k)&&k!=='hand_setup')]]){const group=document.createElement('optgroup');group.label=label;keys.filter(k=>s.gestures[k]).forEach(k=>group.append(new Option(s.gestures[k],k)));el('tune-gesture').append(group)}}
function drawFields(s,force){const key=s.gesture+'-'+s.revision+'-'+JSON.stringify(s.effective);if(!force&&key===fieldsKey)return;fieldsKey=key;el('tune-fields').replaceChildren();for(const channel of s.components){const pair=s.preview?.[channel]||s.effective[channel];if(!pair)continue;const row=document.createElement('tr');row.dataset.channel=channel;const head=document.createElement('th');head.textContent=channel;row.append(head);for(const name of ['on','off']){const cell=document.createElement('td'),input=document.createElement('input');input.type='number';input.min='0';input.step='.01';input.value=pair[name];input.oninput=()=>row.dataset.changed='yes';input.setAttribute('aria-label',channel+' '+name);cell.append(input);row.append(cell)}el('tune-fields').append(row)}}
const reachNames=['left','right','up','down'];function reachValues(){return Object.fromEntries(reachNames.map(name=>[name,Number(el('reach-'+name).value)]))}function reachSummary(values){const width=(values.left+values.right)*(last?.reach?.camera_width||640),height=(values.up+values.down)*(last?.reach?.camera_height||480);return Number.isFinite(width)&&Number.isFinite(height)&&height>0?`Tracking area: ${width.toFixed(1)} × ${height.toFixed(1)} pixels · ${Number(width/height).toFixed(3)}:1`:''}function drawReach(s,force){const r=s.reach||{},key=s.revision+'-'+JSON.stringify(r);if(!r.available){el('reach-summary').textContent='Center your hand before setting movement reach.';for(const name of reachNames)el('reach-'+name).disabled=true;el('reach-save').disabled=el('reach-reset').disabled=true;return}if((force||key!==reachKey)&&!reachDirty){reachKey=key;for(const name of reachNames){const input=el('reach-'+name);input.value=Number(r.values[name]).toFixed(6);input.max=r.limits[name].max;input.disabled=!!r.pending;input.oninput=()=>{reachDirty=true;el('reach-summary').textContent=reachSummary(reachValues())}}}el('reach-summary').textContent=reachDirty?reachSummary(reachValues()):`Tracking area: ${r.dimensions.width} × ${r.dimensions.height} pixels · ${r.dimensions.aspect}:1`;el('reach-save').disabled=busy||r.pending||!reachDirty;el('reach-reset').disabled=busy||r.pending||!r.custom;el('reach-notice').textContent=r.pending?'Saving reach values…':''}
function drawDiagnostic(d={}){const active=!!d.active;show('diagnostic-record',active&&!d.complete);show('diagnostic-cancel',active);show('diagnostic-download',!!d.report);el('diagnostic-start').hidden=active;el('diagnostic-record').disabled=d.phase!=='ready';el('diagnostic-status').textContent=d.report?'Diagnostic complete. The temporary video was deleted.':active?`Step ${d.index+1} of ${d.total}: ${d.title}. ${d.instruction}`:'Nothing is recorded until you start.'}
function draw(s,force=false){last=s;populate(s);el('tune-gesture').value=s.gesture;const step=s.wizard_step||'problem';show('tune-problems',step==='problem');show('tune-gesture-step',step==='gesture');show('tune-center-step',step==='center');show('tune-record-step',['record','recording'].includes(step));show('tune-test-step',['test','save'].includes(step));show('tune-done',step==='done');el('tune-step').textContent=step==='problem'?'Personalize recognition':step==='gesture'?'Choose a gesture':step==='center'?'Find your center':step==='test'||step==='save'?'Try the adjustment':step==='done'?'All set':`Recording ${Math.min(s.completed_phases+1,3)} of 3`;el('tune-coach').textContent=step==='problem'?'What would you like help with?':step==='gesture'?'Choose the control that needs help.':step==='center'?'Your saved center changes only when you ask.':step==='test'||step==='save'?'Use the gesture twice, then relax your hand.':step==='done'?'Nice work!':'I measure landmarks, not pictures.';
el('tune-components').textContent='This adjusts '+s.components.join(', ')+' across every game profile.';el('tune-instruction').textContent=instruction(s);el('tune-readiness').textContent=!s.ready?'Show your whole hand clearly.':!s.stable_ready?'Great — hold there for a moment.':'I can see your hand. Press I’m ready.';el('tune-readiness').className=s.stable_ready?'ready-good':'ready-warn';el('tune-quality').textContent=s.image_quality?.warning||'';el('tune-bar').style.width=`${Math.min(100,s.completed_phases/3*100)}%`;show('tune-record',s.completed_phases<3);show('tune-suggest',s.completed_phases>=3);el('tune-record').disabled=busy||counting||s.recording||!s.stable_ready;el('tune-record').textContent=s.recording?'Recording…':counting?'Get ready…':"I'm ready";el('tune-suggest').disabled=busy||s.completed_phases!==3;el('tune-progress').textContent=s.error||`${s.completed_phases} of 3 recordings complete${s.recording?' · '+s.samples+' clear measurements':''}`;el('tune-fingers').textContent=!s.ready?'Waiting for clear tracking.':'Pose check: '+Object.entries(s.finger_feedback||{}).map(([k,v])=>`${k} ${v.matches?'✓':'not yet'}`).join(' · ');
const test=s.test||{};el('tune-test-progress').textContent=test.passed?'Test passed — ready to save.':`Clean uses: ${test.cycles||0} of 2 · relaxed: ${Number(test.neutral_seconds||0).toFixed(1)} of 3.0 seconds`;el('tune-test').disabled=busy||test.active;el('tune-save').disabled=busy||!test.passed;el('tune-live').textContent=!s.ready?'Show your hand for live values.':s.components.map(k=>`${k}: ${Number(s.measurements[k]??0).toFixed(3)}`).join(' · ');drawFields(s,force);drawReach(s,force);el('tune-preview').disabled=busy||!el('tune-fields').children.length;drawDiagnostic(s.diagnostic)}
async function command(action,extra={}){if(busy)return;busy=true;try{draw(await api(action,extra),true);el('tune-notice').textContent=''}catch(e){el('tune-notice').textContent=e.message}finally{busy=false;if(last)draw(last)}}
async function reachCommand(action){if(busy)return;busy=true;try{const extra=action==='reach_save'?{reach:reachValues()}:{};const state=await api(action,extra);reachDirty=false;draw(state,true);el('reach-notice').textContent=state.reach?.pending?'Saving reach values…':'Reach values saved.'}catch(e){el('reach-notice').textContent=e.message}finally{busy=false;if(last)draw(last)}}
el('tune-switch').onchange=async()=>{enabled=el('tune-switch').checked;reachDirty=false;try{const s=await api(enabled?'begin':'end');el('tune-panel').hidden=!enabled;el('practice-lessons').hidden=enabled;if(enabled)draw(s,true)}catch(e){enabled=false;el('tune-switch').checked=false;el('tune-panel').hidden=false;el('tune-notice').textContent=e.message}};for(const [id,problem] of [['problem-setup','setup'],['problem-difficult','difficult'],['problem-accidental','accidental'],['problem-off-center','off_center']])el(id).onclick=()=>command('choose_problem',{problem});el('tune-choose').onclick=()=>command('select',{gesture:el('tune-gesture').value});el('tune-calibrate').onclick=()=>calibrate();el('tune-center-done').onclick=()=>command('wizard_back');el('tune-record').onclick=async()=>{if(counting)return;counting=true;for(let n=2;n;n--){el('tune-record').textContent=`Starting in ${n}…`;await new Promise(r=>setTimeout(r,1000))}counting=false;command('wizard_record')};el('tune-suggest').onclick=()=>command('suggest');el('tune-test').onclick=()=>command('start_test');el('tune-save').onclick=()=>command('wizard_save');el('tune-again').onclick=el('tune-back').onclick=el('tune-discard').onclick=()=>command('wizard_back');el('tune-preview').onclick=()=>command('preview',{thresholds:pairs()});el('tune-reset').onclick=()=>{if(confirm('Restore the selected gesture components to supplied defaults across all profiles?'))command('reset')};el('reach-save').onclick=()=>reachCommand('reach_save');el('reach-reset').onclick=()=>{if(confirm('Restore full camera-field reach without changing your center or gestures?'))reachCommand('reach_reset')};el('diagnostic-start').onclick=()=>command('diagnostic_begin');el('diagnostic-record').onclick=async()=>{if(counting)return;counting=true;for(let n=2;n;n--){el('diagnostic-status').textContent=`Starting in ${n}…`;await new Promise(r=>setTimeout(r,1000))}counting=false;command('diagnostic_record')};el('diagnostic-cancel').onclick=()=>command('diagnostic_cancel');el('diagnostic-download').onclick=()=>{const blob=new Blob([JSON.stringify(last.diagnostic.report,null,2)+'\n'],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='virtualglove-academy-diagnostic.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
setInterval(async()=>{if(!enabled||polling)return;polling=true;try{const s=await api('heartbeat');if(!busy)draw(s)}catch(e){el('tune-notice').textContent=e.message}finally{polling=false}},250);window.addEventListener('pagehide',()=>{if(enabled)fetch('/api/tuning',{method:'POST',headers:{'Content-Type':'application/json','X-VirtualGlove-Action':'tuning'},body:JSON.stringify({action:'end',session:practiceSession}),keepalive:true}).catch(()=>{})});})();"""
