# Project: VirtualGlove
# File: uno-q/virtualglove-system-shutdown.conf
# Purpose: Recreate the unprivileged shutdown-helper readiness marker during UNO Q boot.
# Author: Iain Bennett
# Copyright (c) 2026 Iain Bennett
# SPDX-License-Identifier: MIT
# Change log:
#   2026-09-03 - Added persistent readiness-marker creation.
# Full history: docs/CHANGELOG.md and Git history.

d /home/arduino/ArduinoApps/virtualglove/data 0755 arduino arduino - -
f /home/arduino/ArduinoApps/virtualglove/data/.shutdown-enabled 0644 arduino arduino - -
