# Project: VirtualGlove
# File: uno-q/virtualglove-camera-recovery.conf
# Purpose: Restore the camera-recovery readiness marker after boot or app replacement.
# Author: Iain Bennett
# Copyright (c) 2026 Iain Bennett
# SPDX-License-Identifier: MIT

f /home/arduino/ArduinoApps/virtualglove/data/.camera-recovery-enabled 0644 arduino arduino - -
