// Exercise Dashboard rapid-fire persistence and live application controls.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(0,'utf8'),nodes=new Map(),listeners={};
function node(){return {hidden:false,disabled:false,checked:false,style:{},dataset:{},value:'',textContent:'',classList:{toggle(){}},setAttribute(k,v){this[k]=v},getAttribute(k){return this[k]},removeAttribute(k){delete this[k]},append(){},replaceChildren(...v){this.children=v}}}
const get=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)};
const status={vision_state:'active',worker_running:true,active_profile:'program_1',vision_profile:'program_1',profile_source:'RetroPie launch hook',game:'Blaster Master (USA).nes',game_session_active:true,connection_configured:true,controller_enabled:true,controller_context_active:true,calibrated:true,detected:true,confidence:1,rapid_fire:{a:false,b:true,default_a:true,default_b:true,override_a:false,override_b:null}};
let registry={games:{'Blaster Master (USA).nes':{profile:'program_1',rapid_a:false}}},revision='one',requests=[];
async function fetch(path,options={}){requests.push([path,options]);if(path.startsWith('/status'))return {ok:true,json:async()=>status};if(path==='/api/games'){const body=JSON.parse(options.body);if(body.action==='save'){registry=JSON.parse(body.document);revision='two'}return {ok:true,json:async()=>({document:JSON.stringify(registry),revision,profiles:['program_1']})}}if(path==='/api/rapid-fire'){const body=JSON.parse(options.body);status.rapid_fire.a=body.rapid_a??true;status.rapid_fire.b=body.rapid_b??true;status.rapid_fire_update={request_id:body.request_id,state:'applied',message:'Applied to the running game.'};return {ok:true,json:async()=>({accepted:true})}}return {ok:true,json:async()=>({})}}
const context={document:{hidden:false,getElementById:get,createElement:node},window:{addEventListener(k,f){(listeners[k]??=[]).push(f)},dispatchEvent(event){for(const fn of listeners[event.type]||[])fn(event)},updateEasterEgg(){}},localStorage:{getItem(){return null},setItem(){}},Event:class{constructor(type){this.type=type}},fetch,setInterval(){},setTimeout(fn){fn()},clearTimeout(){},confirm(){return false},console,Date};
vm.createContext(context);for(const [,script] of html.matchAll(/<script>([\s\S]*?)<\/script>/g))vm.runInContext(script,context);
(async()=>{await new Promise(setImmediate);await vm.runInContext('update()',context);await new Promise(setImmediate);assert.equal(get('rapid-a').checked,false);assert.equal(get('rapid-b').checked,true);assert.equal(get('rapid-save').disabled,true);get('rapid-b').checked=false;get('rapid-b').onchange();assert.equal(get('rapid-save').disabled,false);await get('rapid-save').onclick();assert.deepEqual(registry.games['Blaster Master (USA).nes'],{profile:'program_1',rapid_a:false,rapid_b:false});await vm.runInContext('update()',context);assert.match(get('rapid-notice').textContent,/Saved and applied/);const hot=requests.filter(([path])=>path==='/api/rapid-fire').at(-1);assert.equal(JSON.parse(hot[1].body).rapid_b,false);assert.equal(hot[1].headers['X-VirtualGlove-Action'],'rapid-fire');await get('rapid-defaults').onclick();assert.equal(registry.games['Blaster Master (USA).nes'],'program_1');console.log('Dashboard rapid-fire controls passed.');})().catch(error=>{console.error(error);process.exitCode=1});
