# Project: VirtualGlove
# File: src/virtualglove/play_game.py
# Purpose: Provide the local camera-controlled Rock Paper Scissors web game.
# Author: Iain Bennett
# Copyright (c) 2026 Iain Bennett
# SPDX-License-Identifier: MIT
# Change log:
#   2026-09-06 - Added the first-to-three Pixel Pal challenge.
# Full history: docs/CHANGELOG.md and Git history.

"""Browser content and interaction logic for Rock Paper Scissors."""

PLAY_CONTENT = """<h1>Rock Paper Scissors</h1><p class='lead dashboard-lead'>Face off against Pixel Pal with your VirtualGlove. Make a fist for rock, hold an open palm for paper, or flash a V sign for scissors. First to three wins.</p>
<div class=rps-layout><div class=rps-camera><img class=camera id=rps-camera data-src=/stream alt='Live camera view for Rock Paper Scissors'><div class=camera-centre-target id=rps-camera-target hidden aria-hidden=true></div><div class=camera-idle id=rps-startup role=status aria-live=polite></div><div class=practice-badge>● GAME MODE</div></div>
<section class='card rps-arena' aria-labelledby=rps-status><div class=rps-score><div><span class=label>You</span><strong id=player-score>0</strong></div><span class=versus>FIRST TO 3</span><div><span class=label>Pixel Pal</span><strong id=computer-score>0</strong></div></div>
<div class=rps-callout id=rps-status role=status aria-live=polite><div><strong>Ready?</strong><span>Select Start round, then hold your move on “Shoot!”</span></div></div>
<div class=rps-matchup id=rps-matchup hidden><div class=rps-move><span class=label>You played</span><strong id=player-move>—</strong><span id=player-label>—</span></div><span>VS</span><div class=rps-move><span class=label>Pixel Pal played</span><strong id=computer-move>—</strong><span id=computer-label>—</span></div></div>
<div class=rps-choices aria-label='Choose a move'><button class=rps-choice data-choice=rock type=button><span class=icon aria-hidden=true>✊</span>Rock</button><button class=rps-choice data-choice=paper type=button><span class=icon aria-hidden=true>✋</span>Paper</button><button class=rps-choice data-choice=scissors type=button><span class=icon aria-hidden=true>✌️</span>Scissors</button></div>
<div class=rps-rounds id=rps-rounds aria-label='No rounds played'></div><div class=controls style='justify-content:center'><button id=rps-start type=button>Start round</button></div><p class=notice id=rps-notice>Starting the game camera…</p></section></div>"""

PLAY_STYLE = """
.rps-layout{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(340px,.85fr);gap:14px;align-items:start}.rps-camera{position:relative}.rps-camera .camera{height:min(54vh,500px);aspect-ratio:auto;margin:0}.rps-arena{text-align:center;overflow:hidden}.rps-score{display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:center;margin-bottom:18px}.rps-score strong{display:block;font:900 clamp(34px,7vw,58px)/1 system-ui;color:var(--cyan)}.rps-score .versus{color:var(--muted);font-size:12px}.rps-callout{min-height:102px;display:grid;place-items:center;padding:12px;border:1px solid var(--line);border-radius:12px;background:#090b11}.rps-callout strong{display:block;font:900 clamp(28px,5vw,48px)/1 system-ui}.rps-callout span{display:block;margin-top:8px;color:var(--muted)}.rps-choices{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0}.rps-choice{min-width:0;padding:12px 6px;background:#272d3c}.rps-choice .icon{display:block;font-size:34px;line-height:1.1;margin-bottom:5px}.rps-choice.detected{outline:2px solid var(--cyan);background:#17324b}.rps-choice:disabled{cursor:default}.rps-matchup{display:grid;grid-template-columns:1fr auto 1fr;gap:10px;align-items:center;margin:15px 0}.rps-move{padding:12px;border-radius:10px;background:#11141d}.rps-move strong{display:block;font-size:34px}.rps-rounds{display:flex;justify-content:center;gap:7px;margin-top:8px}.rps-rounds i{width:11px;height:11px;border-radius:50%;background:#303748}.rps-rounds i.won{background:var(--green)}.rps-rounds i.lost{background:var(--red)}
"""

PLAY_SCRIPT = r"""const $=id=>document.getElementById(id);
const MOVES={rock:{icon:'✊',label:'Rock'},paper:{icon:'✋',label:'Paper'},scissors:{icon:'✌️',label:'Scissors'}};
const choiceButtons=[...document.querySelectorAll('.rps-choice')];
let practiceActive=false,phase='idle',playerScore=0,computerScore=0,computerChoice=null,countdownEnds=0,shootEnds=0,candidate=null,candidateSince=0,history=[],calloutKey='',cameraRetryAt=0;
const practiceSession=(globalThis.crypto&&crypto.randomUUID)?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;
async function practice(enabled){const r=await fetch('/api/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:practiceSession,enabled}),keepalive:!enabled});if(!r.ok)throw Error('Game camera request failed.');practiceActive=enabled;return r}
function cameraMessage(message){$('rps-camera').style.display='none';$('rps-camera-target').hidden=true;$('rps-startup').style.display='flex';$('rps-startup').textContent=message}
async function startPractice(){try{await practice(true);cameraRetryAt=0;$('rps-camera').src=$('rps-camera').dataset.src+'?t='+Date.now();$('rps-notice').textContent='Camera ready. Controller transmission is paused while you play.'}catch(e){cameraMessage('Game camera unavailable. Use the buttons to play.');$('rps-notice').textContent='Could not start the game camera. You can still play with the buttons.'}}
function stopPractice(){if(!practiceActive)return;practiceActive=false;fetch('/api/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:practiceSession,enabled:false}),keepalive:true}).catch(()=>{})}
function recognizedMove(s){if(!s.detected||!s.calibrated)return null;if(s.menu_gesture?.pose==='start')return 'scissors';if(s.recognition?.closed_hand)return 'rock';const fingers=s.finger_active||{};if(Object.keys(fingers).length===5&&!Object.values(fingers).some(Boolean)&&!s.menu_gesture?.pose)return 'paper';return null}
function setCallout(title,detail){const key=title+'\n'+detail;if(key===calloutKey)return;calloutKey=key;const box=$('rps-status'),wrap=document.createElement('div'),heading=document.createElement('strong'),description=document.createElement('span');heading.textContent=title;description.textContent=detail;wrap.append(heading,description);box.replaceChildren(wrap)}
function showDetected(move){choiceButtons.forEach(button=>button.classList.toggle('detected',button.dataset.choice===move))}
function drawRounds(){const rounds=$('rps-rounds');rounds.innerHTML=history.map(result=>`<i class="${result}" title="${result==='won'?'Round won':result==='lost'?'Round lost':'Round tied'}"></i>`).join('');rounds.setAttribute('aria-label',history.length?'Round results: '+history.join(', '):'No rounds played')}
function resetMatch(){playerScore=0;computerScore=0;history=[];$('player-score').textContent='0';$('computer-score').textContent='0';$('rps-matchup').hidden=true;drawRounds()}
function startRound(){if(phase==='countdown'||phase==='shoot')return;if(playerScore>=3||computerScore>=3)resetMatch();phase='countdown';candidate=null;candidateSince=0;computerChoice=Object.keys(MOVES)[Math.floor(Math.random()*3)];countdownEnds=Date.now()+3000;$('rps-start').disabled=true;$('rps-matchup').hidden=true;choiceButtons.forEach(button=>button.disabled=true);setCallout('3','Rock…');showDetected(null)}
function finishRound(playerChoice){if(phase!=='shoot')return;phase='result';const wins={rock:'scissors',paper:'rock',scissors:'paper'},tied=playerChoice===computerChoice,won=wins[playerChoice]===computerChoice;let title,detail;if(tied){title='Tie game';detail='Same move — nobody scores.';history.push('tied')}else if(won){playerScore++;title='You win the round!';detail=`${MOVES[playerChoice].label} beats ${MOVES[computerChoice].label}.`;history.push('won')}else{computerScore++;title='Pixel Pal wins';detail=`${MOVES[computerChoice].label} beats ${MOVES[playerChoice].label}.`;history.push('lost')}$('player-score').textContent=String(playerScore);$('computer-score').textContent=String(computerScore);$('player-move').textContent=MOVES[playerChoice].icon;$('player-label').textContent=MOVES[playerChoice].label;$('computer-move').textContent=MOVES[computerChoice].icon;$('computer-label').textContent=MOVES[computerChoice].label;$('rps-matchup').hidden=false;drawRounds();showDetected(playerChoice);if(playerScore>=3||computerScore>=3){title=playerScore>=3?'You beat Pixel Pal!':'Pixel Pal wins the match';detail=(playerScore>=3?'Glove power! ':'Good game! ')+detail;$('rps-start').textContent='Play again'}else $('rps-start').textContent='Next round';setCallout(title,detail);$('rps-start').disabled=false;choiceButtons.forEach(button=>button.disabled=true)}
function missRound(){if(phase!=='shoot')return;phase='result';computerChoice=null;setCallout('No move detected','Try holding your hand pose steady after “Shoot!” You can also use the buttons.');$('rps-matchup').hidden=true;$('rps-start').textContent='Try again';$('rps-start').disabled=false;choiceButtons.forEach(button=>button.disabled=true);showDetected(null)}
function tick(){const now=Date.now();if(phase==='countdown'){const left=countdownEnds-now;if(left<=0){phase='shoot';shootEnds=now+2500;choiceButtons.forEach(button=>button.disabled=false);setCallout('Shoot!','Hold your move steady…')}else{const count=Math.ceil(left/1000),words={3:'Rock…',2:'Paper…',1:'Scissors…'};setCallout(String(count),words[count])}}else if(phase==='shoot'&&now>=shootEnds)missRound()}
async function update(){try{const r=await fetch('/status',{cache:'no-store'});if(!r.ok)throw Error();const s=await r.json(),starting=s.vision_state==='starting',startup=startupMessage(s);if(starting)cameraMessage(startup);else if(!$('rps-camera').getAttribute('src')&&Date.now()>=cameraRetryAt){cameraRetryAt=Date.now()+1000;$('rps-camera').src=$('rps-camera').dataset.src+'?t='+Date.now()}if(!s.practice_mode&&phase==='idle')$('rps-notice').textContent=startup||'Waiting for the game camera…';const move=recognizedMove(s);if(phase==='countdown')showDetected(move);if(phase!=='shoot')return;showDetected(move);if(move!==candidate){candidate=move;candidateSince=move?Date.now():0}else if(move&&Date.now()-candidateSince>=450)finishRound(move)}catch(e){if(phase==='idle')$('rps-notice').textContent='Waiting for VirtualGlove…'}}
$('rps-start').onclick=startRound;choiceButtons.forEach(button=>button.onclick=()=>finishRound(button.dataset.choice));$('rps-camera').onload=()=>{$('rps-camera').style.display='block';$('rps-camera-target').hidden=false;$('rps-startup').style.display='none'};$('rps-camera').onerror=()=>{cameraRetryAt=Date.now()+1000;$('rps-camera').removeAttribute('src');cameraMessage('Camera image unavailable. Reconnecting…')};window.addEventListener('pagehide',stopPractice);choiceButtons.forEach(button=>button.disabled=true);startPractice();setInterval(()=>{if(practiceActive)practice(true).catch(()=>{})},2000);setInterval(tick,50);setInterval(update,75);update();"""
