#!/usr/bin/env python3
# Project: VirtualGlove
# File: scripts/configure-super-glove-ball-core.py
# Purpose: Select the evidence-gated native core or explicit FCEUmm fallback for one ROM.
# Author: Iain Bennett
# Copyright (c) 2026 Iain Bennett
# SPDX-License-Identifier: MIT
# Change log:
#   2026-09-04 - Added reversible native/FCEUmm per-ROM selection.
# Full history: docs/CHANGELOG.md and Git history.

"""Safely select a Super Glove Ball emulator without changing other ROMs."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import tempfile
from pathlib import Path


NATIVE = "lr-nestopia-powerglove"
FALLBACK = "lr-fceumm"
POWER_GLOVE_DEVICE = 517


def settings(path: Path) -> dict[str, str]:
    """Read RetroPie key/value settings while ignoring comments and unknown lines."""
    result = {}
    if not path.exists():
        return result
    for line in path.read_text().splitlines():
        match = re.match(r'^\s*([A-Za-z0-9_-]+)\s*=\s*"(.*)"\s*$', line)
        if match:
            result[match.group(1)] = match.group(2)
    return result


def write_file(path: Path, text: str) -> None:
    """Atomically replace one configuration file and preserve its mode."""
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = path.stat().st_mode & 0o777 if path.exists() else 0o644
    descriptor, temporary = tempfile.mkstemp(prefix="." + path.name + ".", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w") as stream:
            os.fchmod(stream.fileno(), mode)
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def game_key(rom: Path) -> str:
    """Use the same collision-resistant per-ROM key generated by RetroPie runcommand."""
    return "a" + hashlib.md5(("nes" + str(rom) + "\n").encode()).hexdigest()


def replace_setting(text: str, key: str, value: str) -> str:
    """Replace exactly one simple RetroPie setting, preserving unrelated content."""
    line = key + ' = "' + value + '"'
    pattern = re.compile(r"^\s*" + re.escape(key) + r"\s*=.*$", re.MULTILINE)
    if pattern.search(text):
        return pattern.sub(line, text, count=1)
    return text.rstrip() + ("\n" if text.strip() else "") + line + "\n"


def native_options(prefix: Path) -> tuple[Path, str]:
    """Return native input and video pacing overrides, isolated from other cores."""
    path = prefix / "configs/nes/powerglove-native.cfg"
    return path, (
        'input_libretro_device_p1 = "' + str(POWER_GLOVE_DEVICE) + '"\n'
        'video_threaded = "false"\n'
    )


def native_registration(prefix: Path) -> tuple[Path, str, Path, str]:
    """Return the menu entry and device override without selecting a ROM."""
    configs = prefix / "configs"
    system_path = configs / "nes/emulators.cfg"
    system_text = system_path.read_text()
    system = settings(system_path)
    fallback_core = prefix / "libretrocores/lr-fceumm/fceumm_libretro.so"
    native_core = prefix / "libretrocores/lr-nestopia-powerglove/nestopia_powerglove_libretro.so"
    if not fallback_core.is_file() or FALLBACK not in system:
        raise ValueError("FCEUmm is required so the rollback remains available.")
    if not native_core.is_file():
        raise ValueError("Build and install lr-nestopia-powerglove before registering it.")
    template = system[FALLBACK]
    command = re.sub(r"(?<=-L )\S+", str(native_core), template, count=1)
    if command == template or "%ROM%" not in command:
        raise ValueError("Cannot derive a safe native launch command from lr-fceumm.")
    option_path, option_text = native_options(prefix)
    # RetroArch does not consistently apply input_libretro_device_p1 early
    # enough for this core on RetroPie. Force the same validated device ID on
    # the command line so retro_set_controller_port_device() is called for
    # port 1 before the ROM begins polling the glove.
    command = command.replace(
        "%ROM%",
        "--device=1:" + str(POWER_GLOVE_DEVICE) + " --appendconfig " + str(option_path) + " %ROM%",
        1,
    )
    command = "VIRTUALGLOVE_NATIVE_STATE=/run/virtualglove/native-state " + command
    return system_path, replace_setting(system_text, NATIVE, command), option_path, option_text


def register_native(prefix: Path) -> None:
    """Expose both cores in the launch menu without changing any ROM selection."""
    system_path, system_text, option_path, option_text = native_registration(prefix)
    write_file(system_path, system_text)
    write_file(option_path, option_text)


def plan(prefix: Path, rom: Path, mode: str) -> tuple[Path, str, Path, str]:
    """Validate installed cores and return the two bounded configuration updates."""
    configs = prefix / "configs"
    system_path = configs / "nes/emulators.cfg"
    games_path = configs / "all/emulators.cfg"
    system_text = system_path.read_text()
    system = settings(system_path)
    fallback_core = prefix / "libretrocores/lr-fceumm/fceumm_libretro.so"
    native_core = prefix / "libretrocores/lr-nestopia-powerglove/nestopia_powerglove_libretro.so"
    if not fallback_core.is_file() or FALLBACK not in system:
        raise ValueError("FCEUmm is required so the rollback remains available.")
    if mode == "native":
        system_path, system_text, _, _ = native_registration(prefix)
        selected = NATIVE
    else:
        selected = FALLBACK
    games_text = games_path.read_text() if games_path.exists() else ""
    games_text = replace_setting(games_text, game_key(rom), selected)
    return system_path, system_text, games_path, games_text


def main(argv=None) -> int:
    """Preview or apply native/fallback selection for one exact ROM path."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rom", type=Path, required=True)
    parser.add_argument("--mode", choices=("native", "fceumm"), required=True)
    parser.add_argument("--prefix", type=Path, default=Path("/opt/retropie"))
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args(argv)
    if not args.rom.is_file():
        raise ValueError("ROM path does not exist.")
    system_path, system_text, games_path, games_text = plan(args.prefix, args.rom, args.mode)
    if args.apply:
        write_file(system_path, system_text)
        write_file(games_path, games_text)
        if args.mode == "native":
            register_native(args.prefix)
        print("Selected " + ("native Nestopia" if args.mode == "native" else "FCEUmm fallback") + " for " + args.rom.name)
    else:
        print("PREVIEW " + args.rom.name + " -> " + (NATIVE if args.mode == "native" else FALLBACK))
        print("Run again with --apply to save this per-ROM choice.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
