#!/usr/bin/env python3
# Project: VirtualGlove
# File: scripts/stamp-firmware-version.py
# Purpose: Generate and verify the matrix firmware's source fingerprint.
# Author: Iain Bennett
# Copyright (c) 2026 Iain Bennett
# SPDX-License-Identifier: MIT
# Change log:
#   2026-09-06 - Add an on-device firmware identity independent of Linux deployment.
# Full history: docs/CHANGELOG.md and Git history.

"""Run after editing the sketch; packaging rejects stale firmware stamps."""
import argparse
from pathlib import Path
import runpy


def main():
    """Write the source fingerprint header, or verify it without changing files."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    versioning = runpy.run_path(str(root / "src/virtualglove/versioning.py"))
    identity = versioning["firmware_source_id"](root)
    text = '// Generated by scripts/stamp-firmware-version.py; do not edit.\n#pragma once\n#define VIRTUALGLOVE_FIRMWARE_ID "' + identity + '"\n'
    path = root / "sketch/firmware_version.h"
    if args.check:
        if not path.exists() or path.read_text() != text:
            raise SystemExit("Firmware stamp is stale. Run python3 scripts/stamp-firmware-version.py")
    else:
        path.write_text(text)
    print("Matrix firmware source SHA-256: " + identity)


if __name__ == "__main__":
    main()
